title: Yulyan
description: My Deep Learning Blog
author: Tran T. Vi
logo: /Yulyan-blog/static/img/avatar.png
github: https://github.com/Shindora
about: UIT's Student

baseurl: "https://shindora.github.io/Yulyan-blog"
url: "/Yulyan-blog"

allowsearch: true

disqus_shortname: about
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-paginate
